name: Android CI

on:
  pull_request:
    branches:
      - develop

jobs:
  android:
    uses: RefactoringLifeSocial/devops/.github/workflows/android-ci.yml@main

  marker:
    runs-on: ubuntu-latest
    needs: android
    steps:
      - run: echo "Pipeline Android CI completado ✅"